"""ml models and stock counts

Revision ID: 590c9c3a2981
Revises: ede0c8f0a766
Create Date: 2026-06-14 22:13:03.628144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590c9c3a2981'
down_revision = 'ede0c8f0a766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('mlflow_run_id', sa.String(length=64), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_models_model_type'), ['model_type'], unique=False)

    op.create_table('predictions',
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_type', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_prediction_type'), ['prediction_type'], unique=False)

    op.create_table('stock_counts',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('validated_by_id', sa.String(length=36), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('stock_count_lines',
    sa.Column('stock_count_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('theoretical_quantity', sa.Integer(), nullable=False),
    sa.Column('counted_quantity', sa.Integer(), nullable=True),
    sa.Column('variance', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['stock_count_id'], ['stock_counts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_count_id', 'product_id', name='uq_stock_count_line_product')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_count_lines')
    op.drop_table('stock_counts')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_prediction_type'))
        batch_op.drop_index(batch_op.f('ix_predictions_entity_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_created_at'))

    op.drop_table('predictions')
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_model_type'))

    op.drop_table('ml_models')
    # ### end Alembic commands ###
